spring:
  profiles:
    active: develoment
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dmall?characterEncoding=utf-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.dmall.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml

logging:
  file: dmall.log
#  level:
#    com:
#      dmall: error

